name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build CSS
        run: npm run tailwind:build
      - name: Build Windows EXE
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist:win:all
      - name: Get version from package.json
        id: package-version
        run: |
          $version = node -p "require('./package.json').version"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Create Release and Upload Assets
        run: |
          gh release create ${{ github.ref_name }} `
            --title "الإصدار ${{ steps.package-version.outputs.VERSION }}" `
            --latest `
            "./dist/Restaurant-Setup-${{ steps.package-version.outputs.VERSION }}.exe" `
            "./dist/Restaurant-Setup-${{ steps.package-version.outputs.VERSION }}.msi" `
            "./dist/latest.yml"
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
